options:
  install-sources:
    type: string
    default: |
      - "ppa:opencontrail/ppa"
      - "ppa:opencontrail/r2.20"
    description: Package sources for install
  install-keys:
    type: string
    description: Apt keys for package install sources
  port:
    type: int
    default: 8080
    description: Port to listen for HTTP requests on.
  logo-url:
    type: string
    default: ""
    description: |
      Optional URL to an image file with the site logo
      to be used.
      NOTE: it will get downloaded and cached every time
      the config is updated. If empty, the default will
      be used.
  favicon-url:
    type: string
    default: ""
    description: |
      Optional URL to an icon file with the site favicon
      to be used.
      NOTE: it will get downloaded and cached every time
      the config is updated. If empty, the default will
      be used.
